blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDeleteView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='title')
    slug = models.CharField(max_length=50, verbose_name='slug')
    content = models.TextField(verbose_name='content')
    preview = models.ImageField(upload_to='products/', verbose_name='preview', **NULLABLE)
    date_of_creation = models.DateField(auto_now_add=True, verbose_name='date of creation')
    is_published = models.BooleanField(default=True, verbose_name='publish status')
    count_of_views = models.PositiveIntegerField(default=0, verbose_name='count of views', editable=False)

    def __str__(self):
        return f'{self.title}.'

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'
        ordering = ('title',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ["title", "content", "preview"]
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    extra_context = {'title': 'Blogs'}

    def get_queryset(self, *args, **kwargs):
        """Выводить только те, у которых положительный признак публикации"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ["title", "content", "preview", "is_published"]

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:list")


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """  Увеличивает количество просмотров """

        self.object = super().get_object(queryset)
        self.object.count_of_views += 1
        self.object.save(update_fields=['count_of_views'])
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Do you want to delete this post "{{ object.title }}"? </p>
                        <button type="submit" class="btn btn-success">
                            Confirm
                        </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-danger"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col">
    <div class="card shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            {% if object.preview %}
            <img src="/media/{{ object.preview }}" width="419" height="400" />

            {% endif %}
            <rect width="100%" height="100%" fill="#55595c"/>

        </svg>
        <div class="card-body">
            <p class="card-text">{{ object|title }}</p>
            <a href="{% url 'blog:list' %}" type="button" class="btn btn-sm btn-outline-secondary">Back</a>

        </div>
        <div class="card-footer" >Views {{ object.count_of_views }}</div>
        <div class="card-footer" >Date of creation {{ object.date_of_creation }}</div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-9">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Save
                            {% else %}
                            Create
                            {% endif %}

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
<a href="{% url 'blog:create' %}" type="button" class="btn btn-sm btn-outline-secondary">Create post</a>
{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            {% if object.preview %}
            <img src="/media/{{ object.preview }}" width="419" height="400" />
            {% endif %}
            <rect width="100%" height="100%" fill="#55595c"/>

        </svg>
        <div class="card-body">
            <p class="card-text">{{ object|title }}</p>
            <p class="card-text">{{ object.content|truncatechars:30 }}</p>

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                    <a href="{% url 'blog:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                    <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}