blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDeleteView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.apps import UserConfig
from user.views import RegisterView, ProfileView, generate_new_password

app_name = UserConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/generate_password/', generate_new_password, name='generate_password')
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    phone_number = models.CharField(max_length=35, verbose_name='phone number', **NULLABLE)
    preview = models.ImageField(upload_to='user/', verbose_name='preview', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='country', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from user.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone_number', 'preview',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

user/views.py
import random

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from user.forms import UserRegisterForm, UserChangeForm, UserProfileForm
from user.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Here we go.',
            message='Now you are registered, dear User.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]

        )

        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Here we go.',
            message='You are successfully changed your email, dear User.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]

        )

        return super().form_valid(form)


def generate_new_password(request):
    chars = ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x',
             'c', 'v', 'b', 'n', 'm', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H',
             'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']

    new_password = ''.join([random.choice(chars) for _ in range(10)])
    send_mail(
        subject='The new password.',
        message=f'Your new password is "{new_password}"',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]

    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('main:index'))

user/templates/user/login.html
{% extends 'main/base.html' %}
{% block content %}


<main class="form-control w-150 m-auto">
  <div class="col-12">

    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Log in</button>


                </div>
            </div>
        </div>

    </form>
</div>
</main>

{% endblock %}

user/templates/user/register.html
{% extends 'main/base.html' %}
{% block content %}


<main class="form-control w-150 m-auto">
  <div class="col-12">

    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Register</button>


                </div>
            </div>
        </div>

    </form>
</div>
</main>

{% endblock %}

user/templates/user/user_form.html
{% extends 'main/base.html' %}
{% block content %}


<main class="form-control w-150 m-auto">
  <div class="col-12">

    <form class="row" method="post">
        <div class="col-6">
            <div class="card">

                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Save</button>


                </div>
            </div>
            <div class="card-body">
                <a href="{% url 'user:generate_password' %}" class="btn btn-warning" style="text-black">Generate the New Password</a>
            </div>
        </div>

    </form>
</div>

</main>

{% endblock %}