blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDeleteView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('user.urls', namespace='user'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ProductListView, ContactView, ProductCreateView, ProductUpdateView, ProductDeleteView,\
                        ProductDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(ProductListView.as_view()), name='index'),
    path('home/', ContactView.as_view(), name='home'),
    path('create_product', ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('view_product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product')
]

main/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name='title')
    description = models.CharField(max_length=1000, verbose_name='description')
    preview = models.ImageField(upload_to='products/', verbose_name='preview', **NULLABLE)
    category = models.ForeignKey('Category', verbose_name='category', on_delete=models.SET_NULL, **NULLABLE)
    price = models.IntegerField(verbose_name='price')
    date_of_creation = models.DateField(verbose_name='date_of_creation')
    date_of_last_change = models.DateField(verbose_name='date_of_last_change')
    is_published = models.BooleanField(default=False, verbose_name='publish status', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='owner')

    def __str__(self):
        return f'{self.title}, {self.description}, {self.category}, {self.price},' \
               f' {self.date_of_creation}, {self.date_of_last_change}, {self.owner}'

    class Meta:

        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('title',)

        permissions = [
            (
                "can_edit_product",
                "Can Edit Product"
            )
        ]


class Category(models.Model):
    title = models.CharField(max_length=150, verbose_name='title')
    description = models.CharField(max_length=1000, verbose_name='description')

    def __str__(self):
        return f'{self.title}, {self.description}'

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('title',)


class Version(models.Model):
    product = models.ForeignKey('Product', verbose_name='product', on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='version number')
    version_title = models.CharField(max_length=150, verbose_name='version title')
    is_version_valid = models.BooleanField(verbose_name='is version valid')

    def __str__(self):
        return f'{self.version_title}, {self.version_number}'

    class Meta:
        verbose_name = 'version'
        verbose_name_plural = 'versions'
        ordering = ('version_number',)

main/forms.py
from django import forms

from main.models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'category', 'date_of_creation', 'date_of_last_change', 'price')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_title(self):
        cleaned_title = self.cleaned_data.get('title')
        cleaned_description = self.cleaned_data.get('description')
        black_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in range(len(black_list)):
            if black_list[word] in cleaned_title:
                raise forms.ValidationError("Bruh. It's forbidden title.")

        for word in range(len(black_list)):
            if cleaned_description is None:
                return cleaned_title
            if black_list[word] in cleaned_description:
                raise forms.ValidationError("Bruh. It's forbidden description.")

        return cleaned_title


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    # def clean_title(self):
    #     cleaned_title = self.cleaned_data.get('title')
    #     cleaned_description = self.cleaned_data.get('description')
    #     black_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
    #     for word in range(len(black_list)):
    #         if black_list[word] in cleaned_title:
    #             raise forms.ValidationError("Bruh. It's forbidden title.")
    #         if cleaned_description is None:
    #             return cleaned_title
    #
    #     for word in range(len(black_list)):
    #         if cleaned_description is None:
    #             return cleaned_title
    #         if black_list[word] in cleaned_description:
    #             raise forms.ValidationError("Bruh. It's forbidden description.")
    #
    #     return cleaned_title

main/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db import transaction
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, TemplateView, UpdateView, DeleteView, DetailView
from pytils.translit import slugify

from main.models import Product, Version
from main.forms import ProductForm, VersionForm


class ProductListView(ListView):
    model = Product
    template_name = 'main/index.html'
    extra_context = {'title': 'Main Page'}


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        context_data = self.get_context_data()

        formset = context_data['formset']
        with transaction.atomic():
            if form.is_valid():
                self.object = form.save()
                if formset.is_valid():
                    formset.instance = self.object
                    formset.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product_formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = product_formset(self.request.POST)
        else:
            context_data['formset'] = product_formset()
        return context_data


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('main:index')
    form_class = ProductForm

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            if form.is_valid():
                self.object = form.save()
                if formset.is_valid():
                    formset.instance = self.object
                    formset.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product_formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = product_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = product_formset(instance=self.object)
        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise PermissionError('Bruh. You are not the owner.')
        return self.object


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'version_list_{self.object.pk}'
            version_list = cache.get(key)
            if version_list is None:
                version_list = self.object.version_set.all()
                cache.set(key, version_list)
        else:
            version_list = self.object.version_set.all()

        context_data['versions'] = version_list
        return context_data


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("main:index")


class ContactView(TemplateView):
    template_name = 'main/home.html'
    extra_context = {
        'title': 'Contacts'
    }

    def get_context_data(self, **kwargs):
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            email = self.request.POST.get('email')
            message = self.request.POST.get('message')
            print(f'You have new message from {name}({email}): {message}')
        return super().get_context_data(**kwargs)

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{{ title }}</title>



    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }

    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">

                </div>
                {% include 'main/includes/inc_main_menu.html'%}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>


            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">&copy; Technical Store "Original" 2004 - {% now 'Y' %}
    </div>
</footer>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

</body>
</html>

main/templates/main/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'main:create' %}">Add content</a>
    </div>
{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            <img src="/media/{{ object.preview }}" width="419" height="400" />
            <rect width="100%" height="100%" fill="#55595c"/>

        </svg>
        <div class="card-body">
            <p class="card-text">{{ object|title }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'main:view' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                    <a href="" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col">
    <div class="card shadow-sm ">

        <div class="card-body">
            <p class="card-text">
                Main office: Prague, Letecka st. 747<br>
                Reserve office: Saint_Petersburg, Tkachey st.22<br>
            </p>
        </div>
    </div>
</div>

<div class="col">
    <div class="card shadow-sm ">
        <div class="card-body">
            <h4>Connect with us</h4>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name" placeholder="Name"/>
                <input class="form-control mb-2" name="email" placeholder="Email"/>
                <textarea class="form-control mb-2" name="message" placeholder="Your message."></textarea>
                <button type="submit" class="btn btn-primary form-control">
                    Submit
                </button>

            </form>


        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <a href="{% url 'main:create_product' %}" type="button" class="btn btn-sm btn-outline-secondary">Add your product</a>
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <img src="/media/{{ object.preview }}" width="419" height="400" />
                <rect width="100%" height="100%" fill="#55595c"/>

            </svg>
            <div class="card-body">
                <p class="card-text">Title: {{ object.title }}</p>

                <p class="card-text">Category: {{ object.category }}</p>

                <p class="card-text">Price: {{ object.price }} rub</p>
                <p class="card-text">User: {{ object.owner|default:"God person" }} </p>


                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'main:view_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'main:edit_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'main:delete_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {% endfor %}
{% else %}
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <img src="/media/{{ object.preview }}" width="419" height="400" />
                <rect width="100%" height="100%" fill="#55595c"/>

            </svg>
            <div class="card-body">
                <p class="card-text">Title: {{ object.title }}</p>

                <p class="card-text">Category: {{ object.category }}</p>

                <p class="card-text">Price: {{ object.price }} rub</p>
                <p class="card-text">User: {{ object.owner|default:"God person" }} </p>


                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'main:view_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'main:edit_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'main:delete_product' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {% endfor %}

{% endif %}

{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-18">
    <div class="row">
        <div class="col-18">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Do you want to delete this post? </p>
                       "{{ object.title }}"<p>
                        {{ form.as_p }}
                        <p><button class="btn btn-primary" type="submit">Confirm</button>
                        <a href="{% url 'main:index' %}" class="btn btn-danger"> Cancel </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col">
    <div class="card shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="0"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            {% if object.preview %}
            <img src="/media/{{ object.preview }}" width="419" height="400" />

            {% endif %}
            <rect width="100%" height="100%" fill="#55595c"/>

        </svg>
        <div class="card-body">
            <p class="card-text">Title: {{ object.title }}</p>
            <p class="card-text">Description: {{ object.description }}</p>
            <p class="card-text">Category: {{ object.category }}</p>

            <p class="card-text">Last change: {{ object.date_of_last_change }}</p>
            <p class="card-text">Price: {{ object.price }} rub</p>
            <a href="{% url 'main:index' %}" type="button" class="btn btn-sm btn-outline-secondary">Back</a>

        </div>

        <div class="card-footer" >Date of creation {{ object.date_of_creation }}</div>
    </div>
</div>

{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}
{% block content %}


<div class="col-12">

    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Save</button>


                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}


                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}